### ISSUE TITLE
No layout: index.html

### ISSUE THREAD

**Issue by anufryieu** [Jamling/hexo-site#1]
Hi!

I did all steps from Readme.

$ git clone https://github.com/Jamling/hexo-site
$ cd hexo-site
$ git clone https://github.com/Jamling/themes/hexo-theme-nova ./themes/nova/
$ npm install
$ hexo s

When I try open localhost:4000 I get warning in console
WARN No Layout: index.html

Any ideas?

**Comment by Jamling** [comment]
Is the theme cloned successfully? The command of cloning theme in your steps seems wrong. The correct command is:
`git clone https://github.com/Jamling/hexo-theme-nova ./themes/nova/`

**Comment by anufryieu** [comment]
yes, the issue was resolved when I changed theme url
